### PR TITLE
Update head title and change favicon to sparkdefi logo

### PR DESCRIPTION
**Pull request by kojiadrianojr**
* Rename "SparkSwap Dex" to "SparkSwap" ( removed Dex ) 
* Change favicon to sparkdefi icon

see picture: 
image
note: it's still the old favicon displayed ( sparkpoint ) because the one uploaded on the absolute link is the sparkpoint logo.

already updated the file favicon to sparkdefi logo

### CODE REVIEW

**Comment by swengr-janan** [comment]
Picture master koj

**Review by swengr-janan — APPROVED** [review]
Basta PR ni master koj, aprub ko yan! Aprub baCk idOL!

**Review by Pseudoman21 — APPROVED** [review]
Accordance!

**Review by ricoz — APPROVED** [review]
Dexless!

**Pull request merged**
