### PR TITLE
Website develop

### PR DESCRIPTION
**Pull request by mativanarquero**
Merge website updates

### CODE REVIEW

**Comment by kojiadrianojr** [comment]
@mativanarquero pull mo branch. and  pa alis na sa draft netong PR. no conflicts na siya

**Review by kojiadrianojr — COMMENTED** [review]
Please add features and note @mativanarquero that this is prototype and a new mockup is at work.

**Comment by kojiadrianojr** [comment]
di parin nadala nung paayos pare?

**Comment by kojiadrianojr** [comment]
Ayun wala na @mativanarquero  <3
Thanks parekoy

**Comment by mativanarquero** [comment]
> di parin nadala nung paayos pare?

Updated. Pacheck semi-master @kojiadrianojr

**Comment by mativanarquero** [comment]
> Ayun wala na @mativanarquero <3 Thanks parekoy

Thank you as well @kojiadrianojr

**Pull request closed without merging**
