### PR TITLE
Supported crypto section and title component

### LINKED ISSUE #132: [website] supported crypto section component

### PR DESCRIPTION
**Pull request by justinbalaguer**
Closes #132 
image

### CODE REVIEW

**Comment by kojiadrianojr** [comment]
@justinbalaguer pa tag nung issue na tig set mo saka sa gh projects

**Comment by justinbalaguer** [comment]
> @justinbalaguer pa tag nung issue na tig set mo saka sa gh projects

tama ba ini? tig tag ko sa dito sa comment tapos tig link ko sa gh projects?

**Comment by mativanarquero** [comment]
> > @justinbalaguer pa tag nung issue na tig set mo saka sa gh projects
> 
> tama ba ini? tig tag ko sa dito sa comment tapos tig link ko sa gh projects?



> Resolves #132 image



> Resolves #132 image

Closes nalang instead of resolves @justinbalaguer para automatically ma-close na yung issue

**Comment by justinbalaguer** [comment]
> Closes nalang instead of resolves @justinbalaguer para automatically ma-close na yung issue

sigs sigs

**Review by acirrej — APPROVED** [review]

**Review by swengr-janan — APPROVED** [review]

**Pull request merged**
