### PR TITLE
Add notification for transactions

### PR DESCRIPTION
**Pull request by kojiadrianojr**
Changes: 

✅ Add transaction notification
image

### CODE REVIEW

**Review by harveyjavier — APPROVED** [review]
Notified!

**Review by Pseudoman21 — APPROVED** [review]
Informed!

**Review by swengr-janan — CHANGES_REQUESTED** [review]
Change "bscscan" to "BscScan"

**Comment by kojiadrianojr** [comment]
> Change "bscscan" to "BscScan"

done

**Review by swengr-janan — APPROVED** [review]
Added!

**Comment by kojiadrianojr** [comment]
pa deploy nalang if satisfied na keyu mga master @aldrickb @medardm

**Pull request merged**
