### PR TITLE
Add Ownly to token list

### PR DESCRIPTION
**Pull request by kojiadrianojr**
image

Please check token list info

### CODE REVIEW

**Review by harveyjavier — APPROVED** [review]
Iconic!

**Review by swengr-janan — APPROVED** [review]

**Comment by swengr-janan** [comment]
SLOW HANDS

**Comment by harveyjavier** [comment]
HAHA sorry balpz!

**Comment by swengr-janan** [comment]
HAHAHAHAHA ALL 🐐 IN THE HOOD

**Pull request merged**
