### PR TITLE
Add custom BSC TestNet configuration

### PR DESCRIPTION
**Pull request by aldrickb**
To add configuration for BSC MainNet, notes are as follows:

(src/constants/index.ts)
ROUTER_ADDRESS to update - Deploy Router contract to BSC MainNet and TestNet with a similar contract address

(src/constants/multicall/index.ts)
MultiCall MainNet address to update - Currently, the MainNet address is the same as TestNet

(src/constants/token/pancakeswap.json)
Add bSRK MainNet token info - Currently, only SRK TestNet is added

(src/constants/v1/index.ts)
V1_FACTORY_ADDRESS MainNet address to update - Currently, the MainNet address is the same as TestNet

Others:
Update NPM modules sources from @aldrickb to @sparkpointio

### CODE REVIEW

**Comment by aldrickb** [comment]
Hotlink to the test transaction recording: https://sparkpointio.slack.com/archives/C01JYHQB2BS/p1613977591008000
Cannot upload the test transaction recording.

**Review by ricoz — APPROVED** [review]
Testable!

**Review by harveyjavier — APPROVED** [review]
Debuggable!

**Review by medardm — APPROVED** [review]
LGTM

**Review by kojiadrianojr — APPROVED** [review]
Koji approves!

**Pull request merged**
