### PR TITLE
center elements

### LINKED ISSUE #291: Center the elements inside the box
Screen Shot 2022-07-13 at 10 56 57 AM

The reason is the other elements are centered.

### PR DESCRIPTION
**Pull request by justinbalaguer**
Closes #291 
image

### CODE REVIEW

**Review by acirrej — CHANGES_REQUESTED** [review]
Sa responsive 500x800
image

@justinbalaguer

**Comment by justinbalaguer** [comment]
> Sa responsive 500x800 image
> 
> @justinbalaguer

pano dapat layout neto? ibaba ko launch app tapos back to top? check mo din sa live tig baba ko lang kaya ito na back to top haha

**Comment by acirrej** [comment]
image
ganito @justinbalaguer

**Comment by justinbalaguer** [comment]
@acirrej arog na lang kaini ginibo ko. dae ko kaya nabababa. tas dae na kasyahon.
image

**Comment by acirrej** [comment]
sige sige g na yan

**Review by acirrej — APPROVED** [review]
LGTM

**Pull request merged**
