### PR TITLE
Website team section

### LINKED ISSUE #140: [website] team section component

### PR DESCRIPTION
**Pull request by mativanarquero**
Closes #140 
team_1

### CODE REVIEW

**Review by kojiadrianojr — APPROVED** [review]
👍LGTM!

**Comment by swengr-janan** [comment]
Screen Shot 2022-05-26 at 6 44 55 PM

@mativanarquero , sa screen size ko wara dukuton na sa gilid

**Comment by mativanarquero** [comment]
> Screen Shot 2022-05-26 at 6 44 55 PM
> 
> @mativanarquero , sa screen size ko wara dukuton na sa gilid

2560 by 1660 po @swengr-janan? Sa end ko good naman
image

**Review by swengr-janan — APPROVED** [review]

**Pull request merged**
