### PR TITLE
[style/feat] new style for title, sfuel token sections, dynamic data

### PR DESCRIPTION
**Pull request by justinbalaguer**
new style for title
sfuel token sections
dynamic data from api
add token to metamask functionality
copy functionality
powered by binance component
asset update

image

### CODE REVIEW

**Review by acirrej — APPROVED** [review]

**Review by swengr-janan — CHANGES_REQUESTED** [review]
1. Add to MetaMask button is directed to SRK. Please change to SFUEL
2. Change SparkDeFi to SparkSwap

**Comment by kojiadrianojr** [comment]
May napansin palan ako dito sa add to metamask, dapat ata if di naka login yung metamask, may `connect to wallet na button` jan? or nah?

**Comment by swengr-janan** [comment]
Oks na yan tolitz @kojiadrianojr , di man sya web app or dapp, bale maga open nalang si metamask login pag di pa naka log in.

**Review by swengr-janan — APPROVED** [review]
AGITHIIAFGM!

**Pull request merged**
