### PR TITLE
Unlock and platform sections, barrel website components

### LINKED ISSUE #208: Add barrels for website components

### PR DESCRIPTION
**Pull request by mativanarquero**
Closes #208 
References #210 
References #209 
t_p

* Create barrels for website components 
* Unlock animation asset to be followed once asset is ready
* Platform UI enhancements (in-reference with v2 mock-up)
  - Improved section aesthetics to better match website's overall design language
  - Improved UX experience by reducing button clicks for a better and more accessible section information
 
Platform section | V2 initial mock-up:
image

### CODE REVIEW

**Review by swengr-janan — CHANGES_REQUESTED** [review]
Change to SparkSwap
Screen Shot 2022-06-09 at 2 56 03 PM

**Comment by swengr-janan** [comment]
Add coming soon
Screen Shot 2022-06-09 at 3 00 29 PM

**Comment by mativanarquero** [comment]
Add 'Coming Soon' to SparkSwap DAO platform
image

Supply SparkRewards short description
image

Update SparkPool description
image

**Review by swengr-janan — APPROVED** [review]
AGITHIITFGM!

**Pull request merged**
