### PR TITLE
Swap component ui fix

### PR DESCRIPTION
**Pull request by kojiadrianojr**
Update alignment: 
image
image
image

### CODE REVIEW

**Review by swengr-janan — APPROVED** [review]
All hood in the goods!

**Review by harveyjavier — APPROVED** [review]
Fixed!

**Comment by harveyjavier** [comment]
Slow hands! hgaha

**Comment by kojiadrianojr** [comment]
NOTE: Di ko palan nasama yung settings modal pero kasama na yun jan sa fix.

**Comment by swengr-janan** [comment]
Ah oki koj. Confirm ko nalang pag na deploy na ni master @aldrickb

**Comment by swengr-janan** [comment]
Or diretso na ba yan koj?

**Comment by kojiadrianojr** [comment]
Di pa naman ako binigyan go signal ni master @aldrickb .

si master ata mag dedeploy

**Comment by swengr-janan** [comment]
Ah oki oki

**Pull request merged**
