### PR TITLE
Fix cardnav property warning

### PR DESCRIPTION
**Pull request by kojiadrianojr**
image

Modify component to remove the warning 

( except dyan sa api warning for translation yan di naman natin ginamit yan )

### CODE REVIEW

**Comment by mativanarquero** [comment]
Fixed!

**Review by mativanarquero — APPROVED** [review]
Fixed!

**Review by kbaldo — APPROVED** [review]
Warning eradicated!

**Review by swengr-janan — APPROVED** [review]
Fixed!

**Pull request merged**
