### PR TITLE
[ Website ] Contact Us 

### LINKED ISSUE #204: [ WEBSITE ] - Add section - Contact Us

### PR DESCRIPTION
**Pull request by kojiadrianojr**
closes #204

### CODE REVIEW

**Review by acirrej — CHANGES_REQUESTED** [review]
image

makapal masyado fill box and sagad masyado sa left yung text sa kada box

**Review by acirrej — CHANGES_REQUESTED** [review]
image

Sizing ng boxes, paliitin pa, pati yung text size pag nag fill up

**Comment by kojiadrianojr** [comment]
> spacing too big
> 
> Spacing is too big

Wag mo na muna siguro pansin ung ibang hindi concern sa PR kasi this pr is for `Contact Us` 

ibang PR concern kasi yung buong pag and babaguhin rin yung sections jan kaya di ko yan sinama parekoy. 
pero to quote rin, eto yung hati nya parekoy: 
image

**Comment by acirrej** [comment]
Ay sige sige i-note ko nalang yung ibang issues

**Comment by kojiadrianojr** [comment]
PR Updated!

**Review by justinbalaguer — APPROVED** [review]

**Review by swengr-janan — APPROVED** [review]
AGITHIITFGM!

**Pull request merged**
