### PR TITLE
Add LOADING component for amount values when connecting

### LINKED ISSUE #122: Add loading on values

### PR DESCRIPTION
**Pull request by kojiadrianojr**
Closes #122 

image
image

### CODE REVIEW

**Review by mativanarquero — APPROVED** [review]
LGTM!

**Comment by swengr-janan** [comment]
Screen Shot 2022-04-27 at 1 09 04 PM

Tried npm install and yarn install but still, error occurred @kojiadrianojr

**Comment by kojiadrianojr** [comment]
Try mo restart server, or puntta ka sa file na yan tas control save mo. @swengr-janan

**Comment by kojiadrianojr** [comment]
Please avoid using npm kung naka yarn @swengr-janan. gamit natin dito is Yarn magkaka issue yan kasi dalawa gamit natin. Maybe in tthe long run.

**Review by swengr-janan — APPROVED** [review]
AGITH

**Pull request merged**
