### PR TITLE
Fix alignment - Approve and Swap Buttons

### PR DESCRIPTION
**Pull request by mativanarquero**
swap_ui

### CODE REVIEW

**Comment by swengr-janan** [comment]
Fixed naman na yung placement ng buttons na yan no @mativanarquero ? Kahit dumagdag/bawas text sa taas di sya gumagalaw?

**Review by harveyjavier — APPROVED** [review]
Aligned!

**Comment by mativanarquero** [comment]
> Fixed naman na yung placement ng buttons na yan no @mativanarquero ? Kahit dumagdag/bawas text sa taas di sya gumagalaw?

Based on my tests sir with different possible token pairs involving SRK and BNB, alignment remains consistent naman.

**Review by kbaldo — APPROVED** [review]
Fixed!

**Review by kojiadrianojr — APPROVED** [review]
GNYP

**Comment by harveyjavier** [comment]
> GNYP

G Na Yan Pawwehhhh

**Comment by harveyjavier** [comment]
May rebyu pa though si  @swengr-janan and @kbaldo

**Review by swengr-janan — APPROVED** [review]
AGITH!

**Pull request merged**
