### PR TITLE
Add srkb as default output token

### LINKED ISSUE #111: Make SRKb and BNB as default pair when opening sparkswap.finance
image

### PR DESCRIPTION
**Pull request by kojiadrianojr**
closes #111

### CODE REVIEW

**Comment by swengr-janan** [comment]
pahingi screenshot @kojiadrianojr

**Comment by kojiadrianojr** [comment]
need mo siya itest tol yung initial na pagload kasi yan

**Comment by swengr-janan** [comment]
yep yep cloning pa si repo hehe

**Comment by kojiadrianojr** [comment]
wait send tuloy mee image

**Comment by swengr-janan** [comment]
Sigs check ko nalang after. Thansku

**Comment by kojiadrianojr** [comment]
yung initial loading baga kasi yan pri

**Comment by kojiadrianojr** [comment]
parang feature kasi

**Comment by swengr-janan** [comment]
@kojiadrianojr  ganun pa din sya sa akin

**Comment by kojiadrianojr** [comment]
Same branch ?

**Comment by swengr-janan** [comment]
naka test net palan kaya ako

**Comment by swengr-janan** [comment]
okay na @kojiadrianojr  all goods!

**Comment by swengr-janan** [comment]
Screen Shot 2022-04-13 at 3 41 21 PM

**Review by swengr-janan — APPROVED** [review]
AGITH!

**Comment by kojiadrianojr** [comment]
noice siges @swengr-janan thanks !

**Pull request merged**
