### PR TITLE
Change decimal from 3 to 15

### PR DESCRIPTION
**Pull request by kojiadrianojr**
From:
image

Update modal to: 
image

### CODE REVIEW

**Review by swengr-janan — CHANGES_REQUESTED** [review]
Koj, pa tanggal `console.log`

image

**Comment by kojiadrianojr** [comment]
ay sigs checking pa ko other console logs

**Review by swengr-janan — APPROVED** [review]
clear!

**Review by harveyjavier — APPROVED** [review]
Sweet fifteen!

**Pull request merged**
