### PR TITLE
Fix footer margins, footer style, and hero updates

### LINKED ISSUE #260: Footer margin on mobile
image

### LINKED ISSUE #261: Adjust contact us container padding
image

### PR DESCRIPTION
**Pull request by mativanarquero**
Closes #260 
Closes #261
image

### CODE REVIEW

**Review by acirrej — CHANGES_REQUESTED** [review]
image

@mativanarquero 540x720

**Review by kojiadrianojr — APPROVED** [review]
All goods after resolving issue on 560 screen size

**Review by medardm — APPROVED** [review]
LGTM

**Review by acirrej — APPROVED** [review]

**Review by medardm — CHANGES_REQUESTED** [review]
@kojiadrianojr padouble check kan code ni @mativanarquero kung tama in terms of proper na pag responsive kan mga bagay bagay

**Pull request merged**
