### PR TITLE
Add SparkSwap founders section and components

### LINKED ISSUE #193: Add Sir Rico and Sir Andy in the team page. Founders tab

### PR DESCRIPTION
**Pull request by mativanarquero**
Closes #193 

image

### CODE REVIEW

**Comment by swengr-janan** [comment]
naka tab style na yan @mativanarquero ?

**Comment by swengr-janan** [comment]
Screen Shot 2022-06-06 at 12 40 25 PM

ganto @mativanarquero

**Comment by mativanarquero** [comment]
> naka tab style na yan @mativanarquero ?

Naka section po like duman sa screenshot sa SLETI? Tab nalang ba team/founders? Default na naka show is team?

**Comment by swengr-janan** [comment]
tab nalang @mativanarquero , same sa sparkpoint website, beta.sparkpoint.io

**Comment by mativanarquero** [comment]
> Screen Shot 2022-06-06 at 12 40 25 PM
> 
> ganto @mativanarquero

Copy. Behavior kang tab is default is all? tapos tab sections: team and founders

**Review by kojiadrianojr — APPROVED** [review]

**Comment by swengr-janan** [comment]
Naka draft ini @kojiadrianojr hahaha tig approve mo na

**Comment by kojiadrianojr** [comment]
nagcomment lang ako ng poji hahaha

**Comment by kojiadrianojr** [comment]
@mativanarquero pasa mo sakin to. may gagawin akong mas madali para mapagaralan mo

**Comment by mativanarquero** [comment]
t_f
@kojiadrianojr

**Review by swengr-janan — APPROVED** [review]
AGITH!

**Pull request merged**
