### PR TITLE
Add mainnet and testnet configuration

### PR DESCRIPTION
**Pull request by aldrickb**
Add mainnet and testnet configuration and SparkSwap is ready for mainnet and testnet testing.

### CODE REVIEW

**Review by Pseudoman21 — APPROVED** [review]
Configured!

**Review by swengr-janan — APPROVED** [review]
Mastered!

**Review by kojiadrianojr — APPROVED** [review]
New construction option!

**Review by harveyjavier — APPROVED** [review]
Customized!

**Review by clowreed — APPROVED** [review]
Config update complete!

**Review by medardm — APPROVED** [review]
LG!

**Pull request merged**
