### PR TITLE
Update side menu with minimal menu items

### PR DESCRIPTION
**Pull request by aldrickb**
image

### CODE REVIEW

**Review by kojiadrianojr — APPROVED** [review]
Prodigified!

**Review by ricoz — CHANGES_REQUESTED** [review]
Remove Exchange and and Liquidity links if they're not being used

**Comment by aldrickb** [comment]
another button link siya sir para dito
image

**Comment by ricoz** [comment]
> another button link siya sir para dito
> image

Sigs let's keep them, working man sinda?

**Comment by aldrickb** [comment]
yes sir working

**Review by swengr-janan — APPROVED** [review]
Masterrified!

**Review by ricoz — APPROVED** [review]
Minimalized!

**Pull request merged**
